package tang.ming.qiao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tang.ming.qiao.domain.Advertisment;
import tang.ming.qiao.domain.AdvertismentExample;

public interface AdvertismentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisment
     *
     * @mbggenerated
     */
    int countByExample(AdvertismentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisment
     *
     * @mbggenerated
     */
    int deleteByExample(AdvertismentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisment
     *
     * @mbggenerated
     */
    int insert(Advertisment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisment
     *
     * @mbggenerated
     */
    int insertSelective(Advertisment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisment
     *
     * @mbggenerated
     */
    List<Advertisment> selectByExample(AdvertismentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisment
     *
     * @mbggenerated
     */
    Advertisment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisment
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Advertisment record, @Param("example") AdvertismentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisment
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Advertisment record, @Param("example") AdvertismentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Advertisment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Advertisment record);
}