package tang.ming.qiao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tang.ming.qiao.domain.CoursePlan;
import tang.ming.qiao.domain.CoursePlanExample;

public interface CoursePlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    int countByExample(CoursePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    int deleteByExample(CoursePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    int insert(CoursePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    int insertSelective(CoursePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    List<CoursePlan> selectByExample(CoursePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    CoursePlan selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CoursePlan record, @Param("example") CoursePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CoursePlan record, @Param("example") CoursePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CoursePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CoursePlan record);
}