package tang.ming.qiao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tang.ming.qiao.domain.CourseClass;
import tang.ming.qiao.domain.CourseClassExample;

public interface CourseClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_class
     *
     * @mbggenerated
     */
    int countByExample(CourseClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_class
     *
     * @mbggenerated
     */
    int deleteByExample(CourseClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_class
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_class
     *
     * @mbggenerated
     */
    int insert(CourseClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_class
     *
     * @mbggenerated
     */
    int insertSelective(CourseClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_class
     *
     * @mbggenerated
     */
    List<CourseClass> selectByExample(CourseClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_class
     *
     * @mbggenerated
     */
    CourseClass selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_class
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CourseClass record, @Param("example") CourseClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_class
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CourseClass record, @Param("example") CourseClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_class
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CourseClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_class
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CourseClass record);
}