package tang.ming.qiao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tang.ming.qiao.domain.CourseAward;
import tang.ming.qiao.domain.CourseAwardExample;

public interface CourseAwardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_award
     *
     * @mbggenerated
     */
    int countByExample(CourseAwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_award
     *
     * @mbggenerated
     */
    int deleteByExample(CourseAwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_award
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_award
     *
     * @mbggenerated
     */
    int insert(CourseAward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_award
     *
     * @mbggenerated
     */
    int insertSelective(CourseAward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_award
     *
     * @mbggenerated
     */
    List<CourseAward> selectByExample(CourseAwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_award
     *
     * @mbggenerated
     */
    CourseAward selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_award
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CourseAward record, @Param("example") CourseAwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_award
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CourseAward record, @Param("example") CourseAwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_award
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CourseAward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_award
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CourseAward record);
}