package tang.ming.qiao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tang.ming.qiao.domain.CourseBook;
import tang.ming.qiao.domain.CourseBookExample;

public interface CourseBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_book
     *
     * @mbggenerated
     */
    int countByExample(CourseBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_book
     *
     * @mbggenerated
     */
    int deleteByExample(CourseBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_book
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_book
     *
     * @mbggenerated
     */
    int insert(CourseBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_book
     *
     * @mbggenerated
     */
    int insertSelective(CourseBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_book
     *
     * @mbggenerated
     */
    List<CourseBook> selectByExample(CourseBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_book
     *
     * @mbggenerated
     */
    CourseBook selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_book
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CourseBook record, @Param("example") CourseBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_book
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CourseBook record, @Param("example") CourseBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_book
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CourseBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_book
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CourseBook record);
}