package tang.ming.qiao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tang.ming.qiao.domain.TeacherFans;
import tang.ming.qiao.domain.TeacherFansExample;

public interface TeacherFansMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_fans
     *
     * @mbggenerated
     */
    int countByExample(TeacherFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_fans
     *
     * @mbggenerated
     */
    int deleteByExample(TeacherFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_fans
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_fans
     *
     * @mbggenerated
     */
    int insert(TeacherFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_fans
     *
     * @mbggenerated
     */
    int insertSelective(TeacherFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_fans
     *
     * @mbggenerated
     */
    List<TeacherFans> selectByExample(TeacherFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_fans
     *
     * @mbggenerated
     */
    TeacherFans selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_fans
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TeacherFans record, @Param("example") TeacherFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_fans
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TeacherFans record, @Param("example") TeacherFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_fans
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TeacherFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_fans
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TeacherFans record);
}