package tang.ming.qiao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tang.ming.qiao.domain.TeacherVisitor;
import tang.ming.qiao.domain.TeacherVisitorExample;

public interface TeacherVisitorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_visitor
     *
     * @mbggenerated
     */
    int countByExample(TeacherVisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_visitor
     *
     * @mbggenerated
     */
    int deleteByExample(TeacherVisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_visitor
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_visitor
     *
     * @mbggenerated
     */
    int insert(TeacherVisitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_visitor
     *
     * @mbggenerated
     */
    int insertSelective(TeacherVisitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_visitor
     *
     * @mbggenerated
     */
    List<TeacherVisitor> selectByExample(TeacherVisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_visitor
     *
     * @mbggenerated
     */
    TeacherVisitor selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_visitor
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TeacherVisitor record, @Param("example") TeacherVisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_visitor
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TeacherVisitor record, @Param("example") TeacherVisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_visitor
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TeacherVisitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_visitor
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TeacherVisitor record);
}