package tang.ming.qiao.domain;

import java.util.Date;

public class Advertisment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisment.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisment.adv_type
     *
     * @mbggenerated
     */
    private Byte advType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisment.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisment.location
     *
     * @mbggenerated
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisment.begin_date
     *
     * @mbggenerated
     */
    private Date beginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisment.end_date
     *
     * @mbggenerated
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisment.adv_img
     *
     * @mbggenerated
     */
    private String advImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisment.adv_url
     *
     * @mbggenerated
     */
    private String advUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisment.adv_name
     *
     * @mbggenerated
     */
    private String advName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisment.id
     *
     * @return the value of advertisment.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisment.id
     *
     * @param id the value for advertisment.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisment.adv_type
     *
     * @return the value of advertisment.adv_type
     *
     * @mbggenerated
     */
    public Byte getAdvType() {
        return advType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisment.adv_type
     *
     * @param advType the value for advertisment.adv_type
     *
     * @mbggenerated
     */
    public void setAdvType(Byte advType) {
        this.advType = advType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisment.create_time
     *
     * @return the value of advertisment.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisment.create_time
     *
     * @param createTime the value for advertisment.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisment.location
     *
     * @return the value of advertisment.location
     *
     * @mbggenerated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisment.location
     *
     * @param location the value for advertisment.location
     *
     * @mbggenerated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisment.begin_date
     *
     * @return the value of advertisment.begin_date
     *
     * @mbggenerated
     */
    public Date getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisment.begin_date
     *
     * @param beginDate the value for advertisment.begin_date
     *
     * @mbggenerated
     */
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisment.end_date
     *
     * @return the value of advertisment.end_date
     *
     * @mbggenerated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisment.end_date
     *
     * @param endDate the value for advertisment.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisment.adv_img
     *
     * @return the value of advertisment.adv_img
     *
     * @mbggenerated
     */
    public String getAdvImg() {
        return advImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisment.adv_img
     *
     * @param advImg the value for advertisment.adv_img
     *
     * @mbggenerated
     */
    public void setAdvImg(String advImg) {
        this.advImg = advImg == null ? null : advImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisment.adv_url
     *
     * @return the value of advertisment.adv_url
     *
     * @mbggenerated
     */
    public String getAdvUrl() {
        return advUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisment.adv_url
     *
     * @param advUrl the value for advertisment.adv_url
     *
     * @mbggenerated
     */
    public void setAdvUrl(String advUrl) {
        this.advUrl = advUrl == null ? null : advUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisment.adv_name
     *
     * @return the value of advertisment.adv_name
     *
     * @mbggenerated
     */
    public String getAdvName() {
        return advName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisment.adv_name
     *
     * @param advName the value for advertisment.adv_name
     *
     * @mbggenerated
     */
    public void setAdvName(String advName) {
        this.advName = advName == null ? null : advName.trim();
    }
}