package tang.ming.qiao.domain;

public class CourseClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_class.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_class.class_name
     *
     * @mbggenerated
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_class.leaf
     *
     * @mbggenerated
     */
    private Boolean leaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_class.level
     *
     * @mbggenerated
     */
    private Byte level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_class.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_class.parent_id
     *
     * @mbggenerated
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_class.priority
     *
     * @mbggenerated
     */
    private Byte priority;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_class.id
     *
     * @return the value of course_class.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_class.id
     *
     * @param id the value for course_class.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_class.class_name
     *
     * @return the value of course_class.class_name
     *
     * @mbggenerated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_class.class_name
     *
     * @param className the value for course_class.class_name
     *
     * @mbggenerated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_class.leaf
     *
     * @return the value of course_class.leaf
     *
     * @mbggenerated
     */
    public Boolean getLeaf() {
        return leaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_class.leaf
     *
     * @param leaf the value for course_class.leaf
     *
     * @mbggenerated
     */
    public void setLeaf(Boolean leaf) {
        this.leaf = leaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_class.level
     *
     * @return the value of course_class.level
     *
     * @mbggenerated
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_class.level
     *
     * @param level the value for course_class.level
     *
     * @mbggenerated
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_class.status
     *
     * @return the value of course_class.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_class.status
     *
     * @param status the value for course_class.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_class.parent_id
     *
     * @return the value of course_class.parent_id
     *
     * @mbggenerated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_class.parent_id
     *
     * @param parentId the value for course_class.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_class.priority
     *
     * @return the value of course_class.priority
     *
     * @mbggenerated
     */
    public Byte getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_class.priority
     *
     * @param priority the value for course_class.priority
     *
     * @mbggenerated
     */
    public void setPriority(Byte priority) {
        this.priority = priority;
    }
}