package tang.ming.qiao.domain;

import java.util.Date;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_name
     *
     * @mbggenerated
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.v_type
     *
     * @mbggenerated
     */
    private Byte vType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_type
     *
     * @mbggenerated
     */
    private Byte courseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.price
     *
     * @mbggenerated
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.discount
     *
     * @mbggenerated
     */
    private Integer discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.view_qty
     *
     * @mbggenerated
     */
    private Integer viewQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.save_qty
     *
     * @mbggenerated
     */
    private Integer saveQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.comment_qty
     *
     * @mbggenerated
     */
    private Integer commentQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.video_url
     *
     * @mbggenerated
     */
    private String videoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.m_video_url
     *
     * @mbggenerated
     */
    private String mVideoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.download_url
     *
     * @mbggenerated
     */
    private String downloadUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.video_cover
     *
     * @mbggenerated
     */
    private String videoCover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.m_video_cover
     *
     * @mbggenerated
     */
    private String mVideoCover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.begin_date
     *
     * @mbggenerated
     */
    private Date beginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.end_date
     *
     * @mbggenerated
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.multi_course
     *
     * @mbggenerated
     */
    private Boolean multiCourse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.grade
     *
     * @mbggenerated
     */
    private Byte grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.plan_qty
     *
     * @mbggenerated
     */
    private Byte planQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.reg_qty
     *
     * @mbggenerated
     */
    private Byte regQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.t_id
     *
     * @mbggenerated
     */
    private Long tId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.class_id
     *
     * @mbggenerated
     */
    private Long classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_name
     *
     * @return the value of course.course_name
     *
     * @mbggenerated
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_name
     *
     * @param courseName the value for course.course_name
     *
     * @mbggenerated
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.v_type
     *
     * @return the value of course.v_type
     *
     * @mbggenerated
     */
    public Byte getvType() {
        return vType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.v_type
     *
     * @param vType the value for course.v_type
     *
     * @mbggenerated
     */
    public void setvType(Byte vType) {
        this.vType = vType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_type
     *
     * @return the value of course.course_type
     *
     * @mbggenerated
     */
    public Byte getCourseType() {
        return courseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_type
     *
     * @param courseType the value for course.course_type
     *
     * @mbggenerated
     */
    public void setCourseType(Byte courseType) {
        this.courseType = courseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.price
     *
     * @return the value of course.price
     *
     * @mbggenerated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.price
     *
     * @param price the value for course.price
     *
     * @mbggenerated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.discount
     *
     * @return the value of course.discount
     *
     * @mbggenerated
     */
    public Integer getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.discount
     *
     * @param discount the value for course.discount
     *
     * @mbggenerated
     */
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.view_qty
     *
     * @return the value of course.view_qty
     *
     * @mbggenerated
     */
    public Integer getViewQty() {
        return viewQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.view_qty
     *
     * @param viewQty the value for course.view_qty
     *
     * @mbggenerated
     */
    public void setViewQty(Integer viewQty) {
        this.viewQty = viewQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.save_qty
     *
     * @return the value of course.save_qty
     *
     * @mbggenerated
     */
    public Integer getSaveQty() {
        return saveQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.save_qty
     *
     * @param saveQty the value for course.save_qty
     *
     * @mbggenerated
     */
    public void setSaveQty(Integer saveQty) {
        this.saveQty = saveQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.comment_qty
     *
     * @return the value of course.comment_qty
     *
     * @mbggenerated
     */
    public Integer getCommentQty() {
        return commentQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.comment_qty
     *
     * @param commentQty the value for course.comment_qty
     *
     * @mbggenerated
     */
    public void setCommentQty(Integer commentQty) {
        this.commentQty = commentQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.video_url
     *
     * @return the value of course.video_url
     *
     * @mbggenerated
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.video_url
     *
     * @param videoUrl the value for course.video_url
     *
     * @mbggenerated
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.m_video_url
     *
     * @return the value of course.m_video_url
     *
     * @mbggenerated
     */
    public String getmVideoUrl() {
        return mVideoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.m_video_url
     *
     * @param mVideoUrl the value for course.m_video_url
     *
     * @mbggenerated
     */
    public void setmVideoUrl(String mVideoUrl) {
        this.mVideoUrl = mVideoUrl == null ? null : mVideoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.download_url
     *
     * @return the value of course.download_url
     *
     * @mbggenerated
     */
    public String getDownloadUrl() {
        return downloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.download_url
     *
     * @param downloadUrl the value for course.download_url
     *
     * @mbggenerated
     */
    public void setDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl == null ? null : downloadUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.video_cover
     *
     * @return the value of course.video_cover
     *
     * @mbggenerated
     */
    public String getVideoCover() {
        return videoCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.video_cover
     *
     * @param videoCover the value for course.video_cover
     *
     * @mbggenerated
     */
    public void setVideoCover(String videoCover) {
        this.videoCover = videoCover == null ? null : videoCover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.m_video_cover
     *
     * @return the value of course.m_video_cover
     *
     * @mbggenerated
     */
    public String getmVideoCover() {
        return mVideoCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.m_video_cover
     *
     * @param mVideoCover the value for course.m_video_cover
     *
     * @mbggenerated
     */
    public void setmVideoCover(String mVideoCover) {
        this.mVideoCover = mVideoCover == null ? null : mVideoCover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.begin_date
     *
     * @return the value of course.begin_date
     *
     * @mbggenerated
     */
    public Date getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.begin_date
     *
     * @param beginDate the value for course.begin_date
     *
     * @mbggenerated
     */
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.end_date
     *
     * @return the value of course.end_date
     *
     * @mbggenerated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.end_date
     *
     * @param endDate the value for course.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.multi_course
     *
     * @return the value of course.multi_course
     *
     * @mbggenerated
     */
    public Boolean getMultiCourse() {
        return multiCourse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.multi_course
     *
     * @param multiCourse the value for course.multi_course
     *
     * @mbggenerated
     */
    public void setMultiCourse(Boolean multiCourse) {
        this.multiCourse = multiCourse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.grade
     *
     * @return the value of course.grade
     *
     * @mbggenerated
     */
    public Byte getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.grade
     *
     * @param grade the value for course.grade
     *
     * @mbggenerated
     */
    public void setGrade(Byte grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.plan_qty
     *
     * @return the value of course.plan_qty
     *
     * @mbggenerated
     */
    public Byte getPlanQty() {
        return planQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.plan_qty
     *
     * @param planQty the value for course.plan_qty
     *
     * @mbggenerated
     */
    public void setPlanQty(Byte planQty) {
        this.planQty = planQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.reg_qty
     *
     * @return the value of course.reg_qty
     *
     * @mbggenerated
     */
    public Byte getRegQty() {
        return regQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.reg_qty
     *
     * @param regQty the value for course.reg_qty
     *
     * @mbggenerated
     */
    public void setRegQty(Byte regQty) {
        this.regQty = regQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.create_time
     *
     * @return the value of course.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.create_time
     *
     * @param createTime the value for course.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.t_id
     *
     * @return the value of course.t_id
     *
     * @mbggenerated
     */
    public Long gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.t_id
     *
     * @param tId the value for course.t_id
     *
     * @mbggenerated
     */
    public void settId(Long tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.class_id
     *
     * @return the value of course.class_id
     *
     * @mbggenerated
     */
    public Long getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.class_id
     *
     * @param classId the value for course.class_id
     *
     * @mbggenerated
     */
    public void setClassId(Long classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.description
     *
     * @return the value of course.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.description
     *
     * @param description the value for course.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}