package tang.ming.qiao.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CourseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    public CourseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table course
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCourseNameIsNull() {
            addCriterion("course_name is null");
            return (Criteria) this;
        }

        public Criteria andCourseNameIsNotNull() {
            addCriterion("course_name is not null");
            return (Criteria) this;
        }

        public Criteria andCourseNameEqualTo(String value) {
            addCriterion("course_name =", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameNotEqualTo(String value) {
            addCriterion("course_name <>", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameGreaterThan(String value) {
            addCriterion("course_name >", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameGreaterThanOrEqualTo(String value) {
            addCriterion("course_name >=", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameLessThan(String value) {
            addCriterion("course_name <", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameLessThanOrEqualTo(String value) {
            addCriterion("course_name <=", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameLike(String value) {
            addCriterion("course_name like", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameNotLike(String value) {
            addCriterion("course_name not like", value, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameIn(List<String> values) {
            addCriterion("course_name in", values, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameNotIn(List<String> values) {
            addCriterion("course_name not in", values, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameBetween(String value1, String value2) {
            addCriterion("course_name between", value1, value2, "courseName");
            return (Criteria) this;
        }

        public Criteria andCourseNameNotBetween(String value1, String value2) {
            addCriterion("course_name not between", value1, value2, "courseName");
            return (Criteria) this;
        }

        public Criteria andVTypeIsNull() {
            addCriterion("v_type is null");
            return (Criteria) this;
        }

        public Criteria andVTypeIsNotNull() {
            addCriterion("v_type is not null");
            return (Criteria) this;
        }

        public Criteria andVTypeEqualTo(Byte value) {
            addCriterion("v_type =", value, "vType");
            return (Criteria) this;
        }

        public Criteria andVTypeNotEqualTo(Byte value) {
            addCriterion("v_type <>", value, "vType");
            return (Criteria) this;
        }

        public Criteria andVTypeGreaterThan(Byte value) {
            addCriterion("v_type >", value, "vType");
            return (Criteria) this;
        }

        public Criteria andVTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("v_type >=", value, "vType");
            return (Criteria) this;
        }

        public Criteria andVTypeLessThan(Byte value) {
            addCriterion("v_type <", value, "vType");
            return (Criteria) this;
        }

        public Criteria andVTypeLessThanOrEqualTo(Byte value) {
            addCriterion("v_type <=", value, "vType");
            return (Criteria) this;
        }

        public Criteria andVTypeIn(List<Byte> values) {
            addCriterion("v_type in", values, "vType");
            return (Criteria) this;
        }

        public Criteria andVTypeNotIn(List<Byte> values) {
            addCriterion("v_type not in", values, "vType");
            return (Criteria) this;
        }

        public Criteria andVTypeBetween(Byte value1, Byte value2) {
            addCriterion("v_type between", value1, value2, "vType");
            return (Criteria) this;
        }

        public Criteria andVTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("v_type not between", value1, value2, "vType");
            return (Criteria) this;
        }

        public Criteria andCourseTypeIsNull() {
            addCriterion("course_type is null");
            return (Criteria) this;
        }

        public Criteria andCourseTypeIsNotNull() {
            addCriterion("course_type is not null");
            return (Criteria) this;
        }

        public Criteria andCourseTypeEqualTo(Byte value) {
            addCriterion("course_type =", value, "courseType");
            return (Criteria) this;
        }

        public Criteria andCourseTypeNotEqualTo(Byte value) {
            addCriterion("course_type <>", value, "courseType");
            return (Criteria) this;
        }

        public Criteria andCourseTypeGreaterThan(Byte value) {
            addCriterion("course_type >", value, "courseType");
            return (Criteria) this;
        }

        public Criteria andCourseTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("course_type >=", value, "courseType");
            return (Criteria) this;
        }

        public Criteria andCourseTypeLessThan(Byte value) {
            addCriterion("course_type <", value, "courseType");
            return (Criteria) this;
        }

        public Criteria andCourseTypeLessThanOrEqualTo(Byte value) {
            addCriterion("course_type <=", value, "courseType");
            return (Criteria) this;
        }

        public Criteria andCourseTypeIn(List<Byte> values) {
            addCriterion("course_type in", values, "courseType");
            return (Criteria) this;
        }

        public Criteria andCourseTypeNotIn(List<Byte> values) {
            addCriterion("course_type not in", values, "courseType");
            return (Criteria) this;
        }

        public Criteria andCourseTypeBetween(Byte value1, Byte value2) {
            addCriterion("course_type between", value1, value2, "courseType");
            return (Criteria) this;
        }

        public Criteria andCourseTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("course_type not between", value1, value2, "courseType");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Integer value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Integer value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Integer value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Integer value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Integer value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Integer> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Integer> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Integer value1, Integer value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andDiscountIsNull() {
            addCriterion("discount is null");
            return (Criteria) this;
        }

        public Criteria andDiscountIsNotNull() {
            addCriterion("discount is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountEqualTo(Integer value) {
            addCriterion("discount =", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountNotEqualTo(Integer value) {
            addCriterion("discount <>", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountGreaterThan(Integer value) {
            addCriterion("discount >", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountGreaterThanOrEqualTo(Integer value) {
            addCriterion("discount >=", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountLessThan(Integer value) {
            addCriterion("discount <", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountLessThanOrEqualTo(Integer value) {
            addCriterion("discount <=", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountIn(List<Integer> values) {
            addCriterion("discount in", values, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountNotIn(List<Integer> values) {
            addCriterion("discount not in", values, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountBetween(Integer value1, Integer value2) {
            addCriterion("discount between", value1, value2, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountNotBetween(Integer value1, Integer value2) {
            addCriterion("discount not between", value1, value2, "discount");
            return (Criteria) this;
        }

        public Criteria andViewQtyIsNull() {
            addCriterion("view_qty is null");
            return (Criteria) this;
        }

        public Criteria andViewQtyIsNotNull() {
            addCriterion("view_qty is not null");
            return (Criteria) this;
        }

        public Criteria andViewQtyEqualTo(Integer value) {
            addCriterion("view_qty =", value, "viewQty");
            return (Criteria) this;
        }

        public Criteria andViewQtyNotEqualTo(Integer value) {
            addCriterion("view_qty <>", value, "viewQty");
            return (Criteria) this;
        }

        public Criteria andViewQtyGreaterThan(Integer value) {
            addCriterion("view_qty >", value, "viewQty");
            return (Criteria) this;
        }

        public Criteria andViewQtyGreaterThanOrEqualTo(Integer value) {
            addCriterion("view_qty >=", value, "viewQty");
            return (Criteria) this;
        }

        public Criteria andViewQtyLessThan(Integer value) {
            addCriterion("view_qty <", value, "viewQty");
            return (Criteria) this;
        }

        public Criteria andViewQtyLessThanOrEqualTo(Integer value) {
            addCriterion("view_qty <=", value, "viewQty");
            return (Criteria) this;
        }

        public Criteria andViewQtyIn(List<Integer> values) {
            addCriterion("view_qty in", values, "viewQty");
            return (Criteria) this;
        }

        public Criteria andViewQtyNotIn(List<Integer> values) {
            addCriterion("view_qty not in", values, "viewQty");
            return (Criteria) this;
        }

        public Criteria andViewQtyBetween(Integer value1, Integer value2) {
            addCriterion("view_qty between", value1, value2, "viewQty");
            return (Criteria) this;
        }

        public Criteria andViewQtyNotBetween(Integer value1, Integer value2) {
            addCriterion("view_qty not between", value1, value2, "viewQty");
            return (Criteria) this;
        }

        public Criteria andSaveQtyIsNull() {
            addCriterion("save_qty is null");
            return (Criteria) this;
        }

        public Criteria andSaveQtyIsNotNull() {
            addCriterion("save_qty is not null");
            return (Criteria) this;
        }

        public Criteria andSaveQtyEqualTo(Integer value) {
            addCriterion("save_qty =", value, "saveQty");
            return (Criteria) this;
        }

        public Criteria andSaveQtyNotEqualTo(Integer value) {
            addCriterion("save_qty <>", value, "saveQty");
            return (Criteria) this;
        }

        public Criteria andSaveQtyGreaterThan(Integer value) {
            addCriterion("save_qty >", value, "saveQty");
            return (Criteria) this;
        }

        public Criteria andSaveQtyGreaterThanOrEqualTo(Integer value) {
            addCriterion("save_qty >=", value, "saveQty");
            return (Criteria) this;
        }

        public Criteria andSaveQtyLessThan(Integer value) {
            addCriterion("save_qty <", value, "saveQty");
            return (Criteria) this;
        }

        public Criteria andSaveQtyLessThanOrEqualTo(Integer value) {
            addCriterion("save_qty <=", value, "saveQty");
            return (Criteria) this;
        }

        public Criteria andSaveQtyIn(List<Integer> values) {
            addCriterion("save_qty in", values, "saveQty");
            return (Criteria) this;
        }

        public Criteria andSaveQtyNotIn(List<Integer> values) {
            addCriterion("save_qty not in", values, "saveQty");
            return (Criteria) this;
        }

        public Criteria andSaveQtyBetween(Integer value1, Integer value2) {
            addCriterion("save_qty between", value1, value2, "saveQty");
            return (Criteria) this;
        }

        public Criteria andSaveQtyNotBetween(Integer value1, Integer value2) {
            addCriterion("save_qty not between", value1, value2, "saveQty");
            return (Criteria) this;
        }

        public Criteria andCommentQtyIsNull() {
            addCriterion("comment_qty is null");
            return (Criteria) this;
        }

        public Criteria andCommentQtyIsNotNull() {
            addCriterion("comment_qty is not null");
            return (Criteria) this;
        }

        public Criteria andCommentQtyEqualTo(Integer value) {
            addCriterion("comment_qty =", value, "commentQty");
            return (Criteria) this;
        }

        public Criteria andCommentQtyNotEqualTo(Integer value) {
            addCriterion("comment_qty <>", value, "commentQty");
            return (Criteria) this;
        }

        public Criteria andCommentQtyGreaterThan(Integer value) {
            addCriterion("comment_qty >", value, "commentQty");
            return (Criteria) this;
        }

        public Criteria andCommentQtyGreaterThanOrEqualTo(Integer value) {
            addCriterion("comment_qty >=", value, "commentQty");
            return (Criteria) this;
        }

        public Criteria andCommentQtyLessThan(Integer value) {
            addCriterion("comment_qty <", value, "commentQty");
            return (Criteria) this;
        }

        public Criteria andCommentQtyLessThanOrEqualTo(Integer value) {
            addCriterion("comment_qty <=", value, "commentQty");
            return (Criteria) this;
        }

        public Criteria andCommentQtyIn(List<Integer> values) {
            addCriterion("comment_qty in", values, "commentQty");
            return (Criteria) this;
        }

        public Criteria andCommentQtyNotIn(List<Integer> values) {
            addCriterion("comment_qty not in", values, "commentQty");
            return (Criteria) this;
        }

        public Criteria andCommentQtyBetween(Integer value1, Integer value2) {
            addCriterion("comment_qty between", value1, value2, "commentQty");
            return (Criteria) this;
        }

        public Criteria andCommentQtyNotBetween(Integer value1, Integer value2) {
            addCriterion("comment_qty not between", value1, value2, "commentQty");
            return (Criteria) this;
        }

        public Criteria andVideoUrlIsNull() {
            addCriterion("video_url is null");
            return (Criteria) this;
        }

        public Criteria andVideoUrlIsNotNull() {
            addCriterion("video_url is not null");
            return (Criteria) this;
        }

        public Criteria andVideoUrlEqualTo(String value) {
            addCriterion("video_url =", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlNotEqualTo(String value) {
            addCriterion("video_url <>", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlGreaterThan(String value) {
            addCriterion("video_url >", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlGreaterThanOrEqualTo(String value) {
            addCriterion("video_url >=", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlLessThan(String value) {
            addCriterion("video_url <", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlLessThanOrEqualTo(String value) {
            addCriterion("video_url <=", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlLike(String value) {
            addCriterion("video_url like", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlNotLike(String value) {
            addCriterion("video_url not like", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlIn(List<String> values) {
            addCriterion("video_url in", values, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlNotIn(List<String> values) {
            addCriterion("video_url not in", values, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlBetween(String value1, String value2) {
            addCriterion("video_url between", value1, value2, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlNotBetween(String value1, String value2) {
            addCriterion("video_url not between", value1, value2, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andMVideoUrlIsNull() {
            addCriterion("m_video_url is null");
            return (Criteria) this;
        }

        public Criteria andMVideoUrlIsNotNull() {
            addCriterion("m_video_url is not null");
            return (Criteria) this;
        }

        public Criteria andMVideoUrlEqualTo(String value) {
            addCriterion("m_video_url =", value, "mVideoUrl");
            return (Criteria) this;
        }

        public Criteria andMVideoUrlNotEqualTo(String value) {
            addCriterion("m_video_url <>", value, "mVideoUrl");
            return (Criteria) this;
        }

        public Criteria andMVideoUrlGreaterThan(String value) {
            addCriterion("m_video_url >", value, "mVideoUrl");
            return (Criteria) this;
        }

        public Criteria andMVideoUrlGreaterThanOrEqualTo(String value) {
            addCriterion("m_video_url >=", value, "mVideoUrl");
            return (Criteria) this;
        }

        public Criteria andMVideoUrlLessThan(String value) {
            addCriterion("m_video_url <", value, "mVideoUrl");
            return (Criteria) this;
        }

        public Criteria andMVideoUrlLessThanOrEqualTo(String value) {
            addCriterion("m_video_url <=", value, "mVideoUrl");
            return (Criteria) this;
        }

        public Criteria andMVideoUrlLike(String value) {
            addCriterion("m_video_url like", value, "mVideoUrl");
            return (Criteria) this;
        }

        public Criteria andMVideoUrlNotLike(String value) {
            addCriterion("m_video_url not like", value, "mVideoUrl");
            return (Criteria) this;
        }

        public Criteria andMVideoUrlIn(List<String> values) {
            addCriterion("m_video_url in", values, "mVideoUrl");
            return (Criteria) this;
        }

        public Criteria andMVideoUrlNotIn(List<String> values) {
            addCriterion("m_video_url not in", values, "mVideoUrl");
            return (Criteria) this;
        }

        public Criteria andMVideoUrlBetween(String value1, String value2) {
            addCriterion("m_video_url between", value1, value2, "mVideoUrl");
            return (Criteria) this;
        }

        public Criteria andMVideoUrlNotBetween(String value1, String value2) {
            addCriterion("m_video_url not between", value1, value2, "mVideoUrl");
            return (Criteria) this;
        }

        public Criteria andDownloadUrlIsNull() {
            addCriterion("download_url is null");
            return (Criteria) this;
        }

        public Criteria andDownloadUrlIsNotNull() {
            addCriterion("download_url is not null");
            return (Criteria) this;
        }

        public Criteria andDownloadUrlEqualTo(String value) {
            addCriterion("download_url =", value, "downloadUrl");
            return (Criteria) this;
        }

        public Criteria andDownloadUrlNotEqualTo(String value) {
            addCriterion("download_url <>", value, "downloadUrl");
            return (Criteria) this;
        }

        public Criteria andDownloadUrlGreaterThan(String value) {
            addCriterion("download_url >", value, "downloadUrl");
            return (Criteria) this;
        }

        public Criteria andDownloadUrlGreaterThanOrEqualTo(String value) {
            addCriterion("download_url >=", value, "downloadUrl");
            return (Criteria) this;
        }

        public Criteria andDownloadUrlLessThan(String value) {
            addCriterion("download_url <", value, "downloadUrl");
            return (Criteria) this;
        }

        public Criteria andDownloadUrlLessThanOrEqualTo(String value) {
            addCriterion("download_url <=", value, "downloadUrl");
            return (Criteria) this;
        }

        public Criteria andDownloadUrlLike(String value) {
            addCriterion("download_url like", value, "downloadUrl");
            return (Criteria) this;
        }

        public Criteria andDownloadUrlNotLike(String value) {
            addCriterion("download_url not like", value, "downloadUrl");
            return (Criteria) this;
        }

        public Criteria andDownloadUrlIn(List<String> values) {
            addCriterion("download_url in", values, "downloadUrl");
            return (Criteria) this;
        }

        public Criteria andDownloadUrlNotIn(List<String> values) {
            addCriterion("download_url not in", values, "downloadUrl");
            return (Criteria) this;
        }

        public Criteria andDownloadUrlBetween(String value1, String value2) {
            addCriterion("download_url between", value1, value2, "downloadUrl");
            return (Criteria) this;
        }

        public Criteria andDownloadUrlNotBetween(String value1, String value2) {
            addCriterion("download_url not between", value1, value2, "downloadUrl");
            return (Criteria) this;
        }

        public Criteria andVideoCoverIsNull() {
            addCriterion("video_cover is null");
            return (Criteria) this;
        }

        public Criteria andVideoCoverIsNotNull() {
            addCriterion("video_cover is not null");
            return (Criteria) this;
        }

        public Criteria andVideoCoverEqualTo(String value) {
            addCriterion("video_cover =", value, "videoCover");
            return (Criteria) this;
        }

        public Criteria andVideoCoverNotEqualTo(String value) {
            addCriterion("video_cover <>", value, "videoCover");
            return (Criteria) this;
        }

        public Criteria andVideoCoverGreaterThan(String value) {
            addCriterion("video_cover >", value, "videoCover");
            return (Criteria) this;
        }

        public Criteria andVideoCoverGreaterThanOrEqualTo(String value) {
            addCriterion("video_cover >=", value, "videoCover");
            return (Criteria) this;
        }

        public Criteria andVideoCoverLessThan(String value) {
            addCriterion("video_cover <", value, "videoCover");
            return (Criteria) this;
        }

        public Criteria andVideoCoverLessThanOrEqualTo(String value) {
            addCriterion("video_cover <=", value, "videoCover");
            return (Criteria) this;
        }

        public Criteria andVideoCoverLike(String value) {
            addCriterion("video_cover like", value, "videoCover");
            return (Criteria) this;
        }

        public Criteria andVideoCoverNotLike(String value) {
            addCriterion("video_cover not like", value, "videoCover");
            return (Criteria) this;
        }

        public Criteria andVideoCoverIn(List<String> values) {
            addCriterion("video_cover in", values, "videoCover");
            return (Criteria) this;
        }

        public Criteria andVideoCoverNotIn(List<String> values) {
            addCriterion("video_cover not in", values, "videoCover");
            return (Criteria) this;
        }

        public Criteria andVideoCoverBetween(String value1, String value2) {
            addCriterion("video_cover between", value1, value2, "videoCover");
            return (Criteria) this;
        }

        public Criteria andVideoCoverNotBetween(String value1, String value2) {
            addCriterion("video_cover not between", value1, value2, "videoCover");
            return (Criteria) this;
        }

        public Criteria andMVideoCoverIsNull() {
            addCriterion("m_video_cover is null");
            return (Criteria) this;
        }

        public Criteria andMVideoCoverIsNotNull() {
            addCriterion("m_video_cover is not null");
            return (Criteria) this;
        }

        public Criteria andMVideoCoverEqualTo(String value) {
            addCriterion("m_video_cover =", value, "mVideoCover");
            return (Criteria) this;
        }

        public Criteria andMVideoCoverNotEqualTo(String value) {
            addCriterion("m_video_cover <>", value, "mVideoCover");
            return (Criteria) this;
        }

        public Criteria andMVideoCoverGreaterThan(String value) {
            addCriterion("m_video_cover >", value, "mVideoCover");
            return (Criteria) this;
        }

        public Criteria andMVideoCoverGreaterThanOrEqualTo(String value) {
            addCriterion("m_video_cover >=", value, "mVideoCover");
            return (Criteria) this;
        }

        public Criteria andMVideoCoverLessThan(String value) {
            addCriterion("m_video_cover <", value, "mVideoCover");
            return (Criteria) this;
        }

        public Criteria andMVideoCoverLessThanOrEqualTo(String value) {
            addCriterion("m_video_cover <=", value, "mVideoCover");
            return (Criteria) this;
        }

        public Criteria andMVideoCoverLike(String value) {
            addCriterion("m_video_cover like", value, "mVideoCover");
            return (Criteria) this;
        }

        public Criteria andMVideoCoverNotLike(String value) {
            addCriterion("m_video_cover not like", value, "mVideoCover");
            return (Criteria) this;
        }

        public Criteria andMVideoCoverIn(List<String> values) {
            addCriterion("m_video_cover in", values, "mVideoCover");
            return (Criteria) this;
        }

        public Criteria andMVideoCoverNotIn(List<String> values) {
            addCriterion("m_video_cover not in", values, "mVideoCover");
            return (Criteria) this;
        }

        public Criteria andMVideoCoverBetween(String value1, String value2) {
            addCriterion("m_video_cover between", value1, value2, "mVideoCover");
            return (Criteria) this;
        }

        public Criteria andMVideoCoverNotBetween(String value1, String value2) {
            addCriterion("m_video_cover not between", value1, value2, "mVideoCover");
            return (Criteria) this;
        }

        public Criteria andBeginDateIsNull() {
            addCriterion("begin_date is null");
            return (Criteria) this;
        }

        public Criteria andBeginDateIsNotNull() {
            addCriterion("begin_date is not null");
            return (Criteria) this;
        }

        public Criteria andBeginDateEqualTo(Date value) {
            addCriterion("begin_date =", value, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateNotEqualTo(Date value) {
            addCriterion("begin_date <>", value, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateGreaterThan(Date value) {
            addCriterion("begin_date >", value, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateGreaterThanOrEqualTo(Date value) {
            addCriterion("begin_date >=", value, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateLessThan(Date value) {
            addCriterion("begin_date <", value, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateLessThanOrEqualTo(Date value) {
            addCriterion("begin_date <=", value, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateIn(List<Date> values) {
            addCriterion("begin_date in", values, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateNotIn(List<Date> values) {
            addCriterion("begin_date not in", values, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateBetween(Date value1, Date value2) {
            addCriterion("begin_date between", value1, value2, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateNotBetween(Date value1, Date value2) {
            addCriterion("begin_date not between", value1, value2, "beginDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNull() {
            addCriterion("end_date is null");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNotNull() {
            addCriterion("end_date is not null");
            return (Criteria) this;
        }

        public Criteria andEndDateEqualTo(Date value) {
            addCriterion("end_date =", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotEqualTo(Date value) {
            addCriterion("end_date <>", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThan(Date value) {
            addCriterion("end_date >", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThanOrEqualTo(Date value) {
            addCriterion("end_date >=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThan(Date value) {
            addCriterion("end_date <", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThanOrEqualTo(Date value) {
            addCriterion("end_date <=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIn(List<Date> values) {
            addCriterion("end_date in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotIn(List<Date> values) {
            addCriterion("end_date not in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateBetween(Date value1, Date value2) {
            addCriterion("end_date between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotBetween(Date value1, Date value2) {
            addCriterion("end_date not between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andMultiCourseIsNull() {
            addCriterion("multi_course is null");
            return (Criteria) this;
        }

        public Criteria andMultiCourseIsNotNull() {
            addCriterion("multi_course is not null");
            return (Criteria) this;
        }

        public Criteria andMultiCourseEqualTo(Boolean value) {
            addCriterion("multi_course =", value, "multiCourse");
            return (Criteria) this;
        }

        public Criteria andMultiCourseNotEqualTo(Boolean value) {
            addCriterion("multi_course <>", value, "multiCourse");
            return (Criteria) this;
        }

        public Criteria andMultiCourseGreaterThan(Boolean value) {
            addCriterion("multi_course >", value, "multiCourse");
            return (Criteria) this;
        }

        public Criteria andMultiCourseGreaterThanOrEqualTo(Boolean value) {
            addCriterion("multi_course >=", value, "multiCourse");
            return (Criteria) this;
        }

        public Criteria andMultiCourseLessThan(Boolean value) {
            addCriterion("multi_course <", value, "multiCourse");
            return (Criteria) this;
        }

        public Criteria andMultiCourseLessThanOrEqualTo(Boolean value) {
            addCriterion("multi_course <=", value, "multiCourse");
            return (Criteria) this;
        }

        public Criteria andMultiCourseIn(List<Boolean> values) {
            addCriterion("multi_course in", values, "multiCourse");
            return (Criteria) this;
        }

        public Criteria andMultiCourseNotIn(List<Boolean> values) {
            addCriterion("multi_course not in", values, "multiCourse");
            return (Criteria) this;
        }

        public Criteria andMultiCourseBetween(Boolean value1, Boolean value2) {
            addCriterion("multi_course between", value1, value2, "multiCourse");
            return (Criteria) this;
        }

        public Criteria andMultiCourseNotBetween(Boolean value1, Boolean value2) {
            addCriterion("multi_course not between", value1, value2, "multiCourse");
            return (Criteria) this;
        }

        public Criteria andGradeIsNull() {
            addCriterion("grade is null");
            return (Criteria) this;
        }

        public Criteria andGradeIsNotNull() {
            addCriterion("grade is not null");
            return (Criteria) this;
        }

        public Criteria andGradeEqualTo(Byte value) {
            addCriterion("grade =", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotEqualTo(Byte value) {
            addCriterion("grade <>", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThan(Byte value) {
            addCriterion("grade >", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThanOrEqualTo(Byte value) {
            addCriterion("grade >=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThan(Byte value) {
            addCriterion("grade <", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThanOrEqualTo(Byte value) {
            addCriterion("grade <=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeIn(List<Byte> values) {
            addCriterion("grade in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotIn(List<Byte> values) {
            addCriterion("grade not in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeBetween(Byte value1, Byte value2) {
            addCriterion("grade between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotBetween(Byte value1, Byte value2) {
            addCriterion("grade not between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andPlanQtyIsNull() {
            addCriterion("plan_qty is null");
            return (Criteria) this;
        }

        public Criteria andPlanQtyIsNotNull() {
            addCriterion("plan_qty is not null");
            return (Criteria) this;
        }

        public Criteria andPlanQtyEqualTo(Byte value) {
            addCriterion("plan_qty =", value, "planQty");
            return (Criteria) this;
        }

        public Criteria andPlanQtyNotEqualTo(Byte value) {
            addCriterion("plan_qty <>", value, "planQty");
            return (Criteria) this;
        }

        public Criteria andPlanQtyGreaterThan(Byte value) {
            addCriterion("plan_qty >", value, "planQty");
            return (Criteria) this;
        }

        public Criteria andPlanQtyGreaterThanOrEqualTo(Byte value) {
            addCriterion("plan_qty >=", value, "planQty");
            return (Criteria) this;
        }

        public Criteria andPlanQtyLessThan(Byte value) {
            addCriterion("plan_qty <", value, "planQty");
            return (Criteria) this;
        }

        public Criteria andPlanQtyLessThanOrEqualTo(Byte value) {
            addCriterion("plan_qty <=", value, "planQty");
            return (Criteria) this;
        }

        public Criteria andPlanQtyIn(List<Byte> values) {
            addCriterion("plan_qty in", values, "planQty");
            return (Criteria) this;
        }

        public Criteria andPlanQtyNotIn(List<Byte> values) {
            addCriterion("plan_qty not in", values, "planQty");
            return (Criteria) this;
        }

        public Criteria andPlanQtyBetween(Byte value1, Byte value2) {
            addCriterion("plan_qty between", value1, value2, "planQty");
            return (Criteria) this;
        }

        public Criteria andPlanQtyNotBetween(Byte value1, Byte value2) {
            addCriterion("plan_qty not between", value1, value2, "planQty");
            return (Criteria) this;
        }

        public Criteria andRegQtyIsNull() {
            addCriterion("reg_qty is null");
            return (Criteria) this;
        }

        public Criteria andRegQtyIsNotNull() {
            addCriterion("reg_qty is not null");
            return (Criteria) this;
        }

        public Criteria andRegQtyEqualTo(Byte value) {
            addCriterion("reg_qty =", value, "regQty");
            return (Criteria) this;
        }

        public Criteria andRegQtyNotEqualTo(Byte value) {
            addCriterion("reg_qty <>", value, "regQty");
            return (Criteria) this;
        }

        public Criteria andRegQtyGreaterThan(Byte value) {
            addCriterion("reg_qty >", value, "regQty");
            return (Criteria) this;
        }

        public Criteria andRegQtyGreaterThanOrEqualTo(Byte value) {
            addCriterion("reg_qty >=", value, "regQty");
            return (Criteria) this;
        }

        public Criteria andRegQtyLessThan(Byte value) {
            addCriterion("reg_qty <", value, "regQty");
            return (Criteria) this;
        }

        public Criteria andRegQtyLessThanOrEqualTo(Byte value) {
            addCriterion("reg_qty <=", value, "regQty");
            return (Criteria) this;
        }

        public Criteria andRegQtyIn(List<Byte> values) {
            addCriterion("reg_qty in", values, "regQty");
            return (Criteria) this;
        }

        public Criteria andRegQtyNotIn(List<Byte> values) {
            addCriterion("reg_qty not in", values, "regQty");
            return (Criteria) this;
        }

        public Criteria andRegQtyBetween(Byte value1, Byte value2) {
            addCriterion("reg_qty between", value1, value2, "regQty");
            return (Criteria) this;
        }

        public Criteria andRegQtyNotBetween(Byte value1, Byte value2) {
            addCriterion("reg_qty not between", value1, value2, "regQty");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andTIdIsNull() {
            addCriterion("t_id is null");
            return (Criteria) this;
        }

        public Criteria andTIdIsNotNull() {
            addCriterion("t_id is not null");
            return (Criteria) this;
        }

        public Criteria andTIdEqualTo(Long value) {
            addCriterion("t_id =", value, "tId");
            return (Criteria) this;
        }

        public Criteria andTIdNotEqualTo(Long value) {
            addCriterion("t_id <>", value, "tId");
            return (Criteria) this;
        }

        public Criteria andTIdGreaterThan(Long value) {
            addCriterion("t_id >", value, "tId");
            return (Criteria) this;
        }

        public Criteria andTIdGreaterThanOrEqualTo(Long value) {
            addCriterion("t_id >=", value, "tId");
            return (Criteria) this;
        }

        public Criteria andTIdLessThan(Long value) {
            addCriterion("t_id <", value, "tId");
            return (Criteria) this;
        }

        public Criteria andTIdLessThanOrEqualTo(Long value) {
            addCriterion("t_id <=", value, "tId");
            return (Criteria) this;
        }

        public Criteria andTIdIn(List<Long> values) {
            addCriterion("t_id in", values, "tId");
            return (Criteria) this;
        }

        public Criteria andTIdNotIn(List<Long> values) {
            addCriterion("t_id not in", values, "tId");
            return (Criteria) this;
        }

        public Criteria andTIdBetween(Long value1, Long value2) {
            addCriterion("t_id between", value1, value2, "tId");
            return (Criteria) this;
        }

        public Criteria andTIdNotBetween(Long value1, Long value2) {
            addCriterion("t_id not between", value1, value2, "tId");
            return (Criteria) this;
        }

        public Criteria andClassIdIsNull() {
            addCriterion("class_id is null");
            return (Criteria) this;
        }

        public Criteria andClassIdIsNotNull() {
            addCriterion("class_id is not null");
            return (Criteria) this;
        }

        public Criteria andClassIdEqualTo(Long value) {
            addCriterion("class_id =", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotEqualTo(Long value) {
            addCriterion("class_id <>", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdGreaterThan(Long value) {
            addCriterion("class_id >", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdGreaterThanOrEqualTo(Long value) {
            addCriterion("class_id >=", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLessThan(Long value) {
            addCriterion("class_id <", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLessThanOrEqualTo(Long value) {
            addCriterion("class_id <=", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdIn(List<Long> values) {
            addCriterion("class_id in", values, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotIn(List<Long> values) {
            addCriterion("class_id not in", values, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdBetween(Long value1, Long value2) {
            addCriterion("class_id between", value1, value2, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotBetween(Long value1, Long value2) {
            addCriterion("class_id not between", value1, value2, "classId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table course
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table course
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}