package tang.ming.qiao.domain;

import java.util.Date;

public class TeacherFans {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_fans.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_fans.t_id
     *
     * @mbggenerated
     */
    private Long tId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_fans.u_id
     *
     * @mbggenerated
     */
    private Long uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_fans.focus_time
     *
     * @mbggenerated
     */
    private Date focusTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_fans.id
     *
     * @return the value of teacher_fans.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_fans.id
     *
     * @param id the value for teacher_fans.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_fans.t_id
     *
     * @return the value of teacher_fans.t_id
     *
     * @mbggenerated
     */
    public Long gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_fans.t_id
     *
     * @param tId the value for teacher_fans.t_id
     *
     * @mbggenerated
     */
    public void settId(Long tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_fans.u_id
     *
     * @return the value of teacher_fans.u_id
     *
     * @mbggenerated
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_fans.u_id
     *
     * @param uId the value for teacher_fans.u_id
     *
     * @mbggenerated
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_fans.focus_time
     *
     * @return the value of teacher_fans.focus_time
     *
     * @mbggenerated
     */
    public Date getFocusTime() {
        return focusTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_fans.focus_time
     *
     * @param focusTime the value for teacher_fans.focus_time
     *
     * @mbggenerated
     */
    public void setFocusTime(Date focusTime) {
        this.focusTime = focusTime;
    }
}